= 3⋮5 Form

image::sphere-glyphs/sphere-03-05.svg[width=100pt,height=141.4pt]

*Form:* ŭm-o͞os /ʌm.us/

Within pattern there emerge forms defined by the pattern and yet independent within it.
These are the first sort of beings which may be described as being and having properties of any sort.

A simple sort of form is number.
Five is a number which has the property of being the first non-sequential prime.
Together with seven it forms the first twin prime pair, seven being prime and two more than five.
The next twin prime pair is eleven and thirteen, followed by seventeen and nineteen, hen twenty-nine and thirty-one.
The sum of all twin prime pairs is divisible by twelve.
All of these properties are found in what they describe, individual units, forms, in an infinite series.

As another example, we may take nearly any game and learn its rules rather quickly, but strategy is an entirely different matter.
Games like Chess or Go give rise to whole vocabularies for naming forms within them.
Though the rules teach us how to play, one must become familiar with these forms to play well.

This tree is formed by budding Form ([.inline]##image:sphere-glyphs/sphere-03-05.svg[]##)
from Chaos ([.inline]##image:sphere-glyphs/sphere-00-01.svg[]##) along path 3 ([.inline]##image:factor-glyphs/0x03.svg[]##).
Paths 4 ([.inline]##image:factor-glyphs/0x04.svg[]##) and 5 ([.inline]##image:factor-glyphs/0x05.svg[]##)
split from paths 0 ([.inline]##image:factor-glyphs/0x00.svg[]##) and 1 ([.inline]##image:factor-glyphs/0x01.svg[]##).

image::diagrams/4-tree-simple.svg[width=65%]

Take a moment to note the balance of 5 in the tree of ŭm-o͞os.
The prime of ŭm-o͞os is five.
The sums of the paths crossing in the middle are also five, as are the sums of the pairs across from each other.
Many patterns of this sort occur as evolution of the trees continue.
