= Emanation

Void spontaneously and for no reason or cause emanates being from non-being.
It is not an action or cause, but rather a permitting.
The narrative of emanation explains this process in a sequence of steps.
Each step is a self-contained emanation complete in itself while continuing to permit further emanation.

In the narrative presented here we present a total of twelve steps.
Each step increases representative power while increasing complexity.
We find that the twelfth step reaches a limit where further complexity diminishes the usefulness of the system.
The system as a whole as presented here is not to be taken as dogma.
While elegance and coherence have been guiding factors,
there are a number of places where choices were made for aesthetic reasons.
You are encouraged to experiment with the system as presented and variations as you may be inspired to explore.

Each emanation contains and is connected to the previous emanations.
The term “sphere” is used as is common in Platonic philosophy to indicate something more than a concept,
a sort of space and realm of ideas.
The term “path” describes the connections between the spheres.
The spheres and paths form a sequence of trees that evolve with each emanation.

Each sphere is given a descriptive name such as "Chaos", "Process", etc.
These names are meant only as a starting point.
There are no words which perfectly suit the meanings generated by the spheres,
and the meanings adapt to whatever context they are applied.

Each sphere is counted in two ways,
once by sequence starting from zero and also by prime number starting from one.
Zero and one represent the identity functions of addition and multiplication.
Each subsequent sphere is then given its own glyph which is produced from merging its sequence and factor glyphs.
The pronunciations of the spheres are similarly generated by combining the pronunciations of these numbers.

Paths are similarly counted in two ways,
once by their order of emanation and also by their order in the Fool's journey.
While the emanation order is set, the Fool's journey depends on the “walkability” of the tree.
This will be explained in detail below.

Experimentation has shown that the placement of paths is usefully thought of as akin to molecular bonds.
The placement of paths are what seems to be the most stable form.
Other less stable and higher-energy forms are possible and quite useful.

Each layer of emanation is named for the sphere which emerges:

0⋮1 - [.inline]##xref:emanation/00-01-chaos.adoc[image:sphere-glyphs/sphere-00-01.svg[] **Chaos**]## +
The first step into being requires no reason or cause.

1⋮2 - [.inline]##xref:emanation/01-02-process.adoc[image:sphere-glyphs/sphere-01-02.svg[] **Process**]## +
The process of being is open and never finished.

2⋮3 - [.inline]##xref:emanation/02-03-pattern.adoc[image:sphere-glyphs/sphere-02-03.svg[] **Pattern**]## +
Everything in being is unified by the pattern which holds it.

3⋮5 - [.inline]##xref:emanation/03-05-form.adoc[image:sphere-glyphs/sphere-03-05.svg[] **Form**]## +
Within pattern occur independent forms.

4⋮7 - [.inline]##xref:emanation/04-07-change.adoc[image:sphere-glyphs/sphere-04-07.svg[] **Change**]## +
Forms are created and destroyed in the flow of time.

5⋮11 - [.inline]##xref:emanation/05-11-agent.adoc[image:sphere-glyphs/sphere-05-11.svg[] **Agent**]## +
Agents direct the flow of change, allowing us to speak of will and intent.

6⋮13 - [.inline]##xref:emanation/06-13-sense.adoc[image:sphere-glyphs/sphere-06-13.svg[] **Sense**]## +
Sense emerges as the experience of the other, the uncontrolled.

7⋮17 - [.inline]##xref:emanation/07-17-thought.adoc[image:sphere-glyphs/sphere-07-17.svg[] **Thought**]## +
Memory forms along with symbolic thought.

8⋮19 - [.inline]##xref:emanation/08-19-desire.adoc[image:sphere-glyphs/sphere-08-19.svg[] **Desire**]## +
Thought gives rise to desire, wanting something different from what is.

9⋮23 - [.inline]##xref:emanation/09-23-matter.adoc[image:sphere-glyphs/sphere-09-23.svg[] **Matter**]## +
Desire manifests objective reality.

10⋮29 - [.inline]##xref:emanation/10-29-soul.adoc[image:sphere-glyphs/sphere-10-29.svg[] **Soul**]## +
Through interplay with objective matter the self becomes encoded and stabilized.

11⋮31 - [.inline]##xref:emanation/11-31-kia.adoc[image:sphere-glyphs/sphere-11-31.svg[] **Kia**]## +
Pure, free, unformed void remains as spirit.

xref:emanation/fools-journey.adoc[**Fool's Journey**] +
Explanation of the sequential path number and naming.
