= Chaos

Why are there beings at all instead of nothing?
This is the fundamental question of philosophy.

Before the narrative of emanation begins we have Void.
What is the nature of Void?
Void is that without any sort of being.
Void has no nature of any sort.
It is impossible to think about void because any thought is not void.
We can, however, point to the nature of Void through apophasis, saying what it is not.

Start with the mundane notion of a void, an empty space, perhaps an empty box.
Take away that the box is any place at all, just focus on the box itself.
The box contains a void but is now surrounded by Void.
It may be difficult to hold this thought as you may find that some sort of place for the box keeps filling in.

Next take away visual appearance of the box.
There is no light by which to see it.
It isn't dark either, there is simply not a visual appearance.
Note the difficulty in imagining a box with no visual appearance.

Now take away any sense of material, then size, and then take away the box altogether,
until void merges with Void.
It may feel expansive, but it is also not this.
Any feeling is not void.

Holding Void in mind is impossible.
The more attributes you strip away the more spaces open and a sort of pressure asserts things into being.
This is because the emptiness of Void is not even empty.
The undefined state holds no constraints on what may follow.

A corollary phenomena is described in quantum physics as superposition.
A physical system, such as the location of an electron in its orbital, is constrained but unspecific.
Given an opportunity for measurement it will assume a value.

This process of Void assuming a value within a constraint is the core of emanation.
