= Emanation

Void spontaneously and for no reason or cause emanates being from non-being.
It is not an action of causing being, but rather merely a permitting.
The narrative of emanation explains this process in a sequence of steps.
Each step is a self-contained emanation complete in itself while continuing to permit further emanation.

In the narative presented here we present a total of twelve steps.
Each step increases representative powerwhile increasing complexity.
We find that the twelfth step reaches a limit where further complexity diminishes the usefulness of the system.
The system as a whole as presented here is not to be taken as dogma.
While elegance and coherence have been guiding factors,
there are a number of places where choices were made for aesthetic reasons.
You are encouraged to experiment with the system as presented and variations as you may be inspired to explore.

Each emanation contains and is connected to the previous emanations.
The term “sphere” is used as is common in Platonic philosophy to indicate something more than a concept,
a sort of place and realm of ideas oriented around a concept.
The term “path” describes the connections between the spheres.
The spheres and paths form a sequence of trees that evolve with each emanation.

Each sphere is counted in two ways,
once by sequence starting from zero and also by prime number starting from one.
Zero and one represent the identity functions of addition and multiplication.
Each subsequent sphere is then given its own glyph which is produced from merging its sequence and factor glyphs.
The pronunciations of the spheres are similarly generated by combining the pronunciations of these numbers.

Paths are similarly counted in two ways,
once by their order of emanation and also by their order in the Fool's journey.
While the emanation order is set, the Fool's journey depends on the “walkability” of the tree.
This will be explained in detail below.

Experimentation has shown that the placement of paths is usefully thought of as akin to molecular bonds.
The placement of paths are what seems to be the most stable form.
Other less stable and higher-energy forms are possible and quite useful.

== Chaos 0⋮1 - nĕsh-hĭn

Existence emerges spontaneously and without reason from Void.
Existence requires no reason.
As the Void has no quality whatsoever it is in no way restricted making it the root generative force.
This is the fundamental nature of existence.
It is spontaneous and without purpose or design.
All possibilities assert themselves into being at once, each becoming a “one”, a unity of existence unto itself while retaining nothing in itself.
