= Emanation

Void spontaneously and for no reason or cause emanates being from non-being.
It is not an action of causing being, but rather a permitting.
The narrative of emanation explains this process in a sequence of steps.
Each step is a self-contained emanation complete in itself while continuing to permit further emanation.

In the narative presented here we present a total of twelve steps.
Each step increases representative powerwhile increasing complexity.
We find that the twelfth step reaches a limit where further complexity diminishes the usefulness of the system.
The system as a whole as presented here is not to be taken as dogma.
While elegance and coherence have been guiding factors,
there are a number of places where choices were made for aesthetic reasons.
You are encouraged to experiment with the system as presented and variations as you may be inspired to explore.

Each emanation contains and is connected to the previous emanations.
The term “sphere” is used as is common in Platonic philosophy to indicate something more than a concept,
a sort of space and realm of ideas.
The term “path” describes the connections between the spheres.
The spheres and paths form a sequence of trees that evolve with each emanation.

Each sphere is given a descriptive name such as "Chaos", "Process", etc.
These names are meant only as a starting point.
There are no words which perfectly suit the meanings generated by the spheres,
and the meanings adapt to whatever context they are applied.

Each sphere is counted in two ways,
once by sequence starting from zero and also by prime number starting from one.
Zero and one represent the identity functions of addition and multiplication.
Each subsequent sphere is then given its own glyph which is produced from merging its sequence and factor glyphs.
The pronunciations of the spheres are similarly generated by combining the pronunciations of these numbers.

Paths are similarly counted in two ways,
once by their order of emanation and also by their order in the Fool's journey.
While the emanation order is set, the Fool's journey depends on the “walkability” of the tree.
This will be explained in detail below.

Experimentation has shown that the placement of paths is usefully thought of as akin to molecular bonds.
The placement of paths are what seems to be the most stable form.
Other less stable and higher-energy forms are possible and quite useful.

== 0⋮1 Chaos

image::sphere-glyphs/sphere-00-01.svg[width=100pt,height=141.4pt]

*Chaos:* nĕsh-hĭn /nɛʃ.hɪn/

Existence emerges spontaneously and without reason from Void.
Existence requires no reason.
As the Void has no quality whatsoever it is in no way restricted, permitting all being to issue forth.
This is the fundamental nature of existence.
It is spontaneous and without purpose or design.
All possibilities assert themselves into being at once, each becoming a “one”, a unity of existence unto itself while retaining nothing in itself.

The union of the zero and one in this first principles resonates with later Platonic philosophical notions of the “unparticipated one”.
It is the universal concept of being itself.
Because it is universal it is present in all things that have any sort of being,
leaving this principle itself without any features.
The numbers zero and one are particularly suited to descrie this first principle because they both reflect methods of leaving a value unchanged;
to add nothing or multiply by one.

The glyph of nĕsh-hĭn, as well as its pronunciation, is produced by the combination of its sequence number, and its “prime” number.
footnote:[One is generally not be considered prime in a similar manner to how zero may be considered to not be a number.]
[.inline]##image:factor-glyphs/0x00.svg[]## and [.inline]##image:factor-glyphs/0x01.svg[]## combine to form [.inline]##image:sphere-glyphs/sphere-00-01.svg[]##.
Likewise “nĭn” and “hĕsh” combine to become “nĕsh-hĭn”.
Similar patterns follow for the glyphs and pronunciation of each sphere.

More of a seed than a tree, we show here a representation of the sphere with its descriptive name, glyph, as well as glyphs for its sequence and prime numbers.

image::diagrams/1-tree-simple.svg[width=30%]

== 1⋮2 Process

image::sphere-glyphs/sphere-01-02.svg[width=100pt,height=141.4pt]

*Process:* hĕzh-ēsh /hɛʒ.iʃ/

That which asserts itself into being does not exhaust possibility.
Every aspect of being is incomplete, retaining its relation to void while constraining and permitting that which may follow.
Each emmanation leaves space for the next emmanation.
All connection is made possible by what is left undetermined
Reality is never fully manifest.

In the tree of hĕzh-ēsh we see the first budding of a sphere and the growth of the first path.
Paths are numbered by the order in which they appear, starting at zero.
The glyph of hĕzh-ēsh and its pronunciation is produced in the same manner as explaned above for nĕsh-hĭn.

image::diagrams/2-tree-simple.svg[width=30%]

== 2⋮3 Pattern

image::sphere-glyphs/sphere-02-03.svg[width=100pt,height=141.4pt]

*Pattern:* ēs-ŭzh /is.ŭʒ/

As the process of manifestation proceeds the shape of the unmanifest spaces influences that which may follow.
This causes patterns to arise that unify the discrete units of being.
Though each is completely free and separate, they are also manifest as a unified pattern.
It is precisely because of incompleteness that these units are able to also become a new unity.

All three of these first spheres describe aspects of being so fundamental as to be universal and therefore ineffable.
First in Chaos ([.inline]##image:sphere-glyphs/sphere-00-01.svg[]##) we have being.
Next in Process ([.inline]##image:sphere-glyphs/sphere-01-02.svg[]##) we have connections between beings, or put another way, multiplicity.
Then in Pattern ([.inline]##image:sphere-glyphs/sphere-02-03.svg[]##) we have the connection that makes a new unity from multiplicity.
All three are subtle and ineffable without any particular instance the mind can grasp.

The sequence of number so far reflects a uniqueness of these first three: 1, 2, 3.
The next prime is 5 and marks a discontinuity.
The first particulars will appear.

In the tree of ēs-ŭzh we see the first branching of the tree.
Path 2 ([.inline]##image:factor-glyphs/0x02.svg[]##) is produced directly from the branching spheres while
path 0 ([.inline]##image:factor-glyphs/0x00.svg[]##) splits to give rise to path 1 ([.inline]##image:factor-glyphs/0x01.svg[]##).

image::diagrams/3-tree-simple.svg[width=60%]

== 3⋮5 Form

image::sphere-glyphs/sphere-03-05.svg[width=100pt,height=141.4pt]

*Form:* ŭm-o͞os /ʌm.us/

Within pattern there emerge forms defined by the pattern and yet independent within it.
This is the first sort of beings.

For example, 5 & 7 are a twin prime pair as they are both prime with a difference of 2.
Other twin primes pairs include 11 & 13, 17 & 19, 29 & 31.
All prime pairs greater than 3 & 5 have the property of having their sum being evenly divisible by 12.
This form of a “prime pair” is known in mathematics but primeness, divisibility, and sums were not in any way defined in order to produce this form.
The pattern of number emanates the form of the prime pair.

As another example, we may take nearly any game and learn its rules rather quickly, but strategy is an entirely different matter.
Games like Chess or Go give rise to whole vocabularies for naming forms within them.
Though the rules teach us how to play, one must become familiar with these forms to play well.

This tree is formed by budding Form ([.inline]##image:sphere-glyphs/sphere-03-05.svg[]##)
from Chaos ([.inline]##image:sphere-glyphs/sphere-00-01.svg[]##) along path 3 ([.inline]##image:factor-glyphs/0x03.svg[]##).
Paths 4 ([.inline]##image:factor-glyphs/0x04.svg[]##) and 5 ([.inline]##image:factor-glyphs/0x05.svg[]##)
split from paths 0 ([.inline]##image:factor-glyphs/0x00.svg[]##) and 1 ([.inline]##image:factor-glyphs/0x01.svg[]##).

image::diagrams/4-tree-simple.svg[width=65%]

Take a moment to note the balance of 5 in the tree of ŭm-o͞os.
The prime of ŭm-o͞os is five.
The sums of the paths crossing in the middle are also five, as are the sums of the pairs across from each other.
Many patterns of this sort occur as evolution of the trees continue.

== 4⋮7 Change

image::sphere-glyphs/sphere-04-07.svg[width=100pt,height=141.4pt]

*Change:* ăou-chăz /aʊ̯.t͡ʃaz/

Manifestation may stop at Form to make a complete but static world.
The universe of number is a perfect example of static manifestation.
Alternately manifestation may remain in flux, in constance state of manifesting and dropping back into Void.
This flux of being is the essence of Change and it is what gives rise to the experience of time.

With Change, manifestation takes on a destructive aspect as forms that come to be now also cease to be.
We move up a level in our analysis to describe types of change and change itself becomes a new type of form.
The mathematically inclined may find it useful to meditate on the relationship of a mathematical function and its derivative.
We may also think of the constant within Change as Will.
Both are implied in the sphere of [.inline]##image:sphere-glyphs/sphere-04-07.svg[]##.

This tree is formed by branching of Change ([.inline]##image:sphere-glyphs/sphere-04-07.svg[]##) from Form ([.inline]##image:sphere-glyphs/sphere-03-05.svg[]##)
along path 7 ([.inline]##image:factor-glyphs/0x07.svg[]##).
Path 6 ([.inline]##image:factor-glyphs/0x06.svg[]##) splits from path 3 ([.inline]##image:factor-glyphs/0x03.svg[]##).
Path 4 ([.inline]##image:factor-glyphs/0x04.svg[]##) remains connected to Form ([.inline]##image:sphere-glyphs/sphere-03-05.svg[]##)
while path 5 ([.inline]##image:factor-glyphs/0x05.svg[]##) follows the new sphere of Change ([.inline]##image:sphere-glyphs/sphere-04-07.svg[]##)

image::diagrams/5-tree-simple.svg[width=80%]

We chose to present the tree in this diagram as a pentagram to show its relationship to the traditional elemental pentagram.
We may take Chaos ([.inline]##image:sphere-glyphs/sphere-00-01.svg[]##) as spirit,
Process ([.inline]##image:sphere-glyphs/sphere-01-02.svg[]##) as water,
Pattern ([.inline]##image:sphere-glyphs/sphere-02-03.svg[]##) as air,
Form ([.inline]##image:sphere-glyphs/sphere-03-05.svg[]##) as earth,
and Change ([.inline]##image:sphere-glyphs/sphere-04-07.svg[]##) as fire to discover a new formulation for a traditional symbol.
More will be said on this later.

Note that this is the first tree where not every sphere has a connection to every other sphere.
This follows a rule constraining the number of paths.
At each emanation the number of the final paths may not exceed the prime number of the final sphere of the tree.
In this case the prime of Change ([.inline]##image:sphere-glyphs/sphere-04-07.svg[]##) is 7 ([.inline]##image:factor-glyphs/0x07.svg[]##)
and so no more paths emerge.

== 5⋮11 Agent

image::sphere-glyphs/sphere-05-11.svg[width=100pt,height=141.4pt]

*Agent:* o͞or-fĕm /uɹ.fɛm/

In the flow of change through time forms emerge which influence change in order to sustain themselves.
These forms are agents of change.
Like the first cellular organisms self-organizing around volcanic vents on the ocean floor in the chemical soup of the earth’s ancient oceans.
The basic aspect of these agents is homeostasis.
These agents direct change to create a dynamic constant.
As these agents guide change we may now call this activity Will.
In the fullness of emanation we come to identify one of these agents with the self.

A great example of an agent is the https://conwaylife.com/wiki/Glider[glider^] in https://conwaylife.com/[Conway's Game of Life^].
This is a self-replicating pattern in a simple automated world, a sort of self-playing game.
This is the simplest sort of agent.
It has no sense of the world or of itself, no facility for planning or wanting.
Further spheres will build from the agent to develop these facilities.

The tree of o͞or-fĕm is formed by budding of Agent ([.inline]##image:sphere-glyphs/sphere-05-11.svg[]##) from Chaos ([.inline]##image:sphere-glyphs/sphere-00-01.svg[]##)
forming path 8 ([.inline]##image:factor-glyphs/0x08.svg[]##).
Paths 9 ([.inline]##image:factor-glyphs/0x09.svg[]##) and 10 ([.inline]##image:factor-glyphs/0x0a.svg[]##)
split from paths 0 ([.inline]##image:factor-glyphs/0x00.svg[]##) and 1 ([.inline]##image:factor-glyphs/0x01.svg[]##).
Paths 3 ([.inline]##image:factor-glyphs/0x03.svg[]##) and 6 ([.inline]##image:factor-glyphs/0x06.svg[]##)
migrate with the new sphere while maintaining their connections to
Form ([.inline]##image:sphere-glyphs/sphere-03-05.svg[]##) and Change ([.inline]##image:sphere-glyphs/sphere-04-07.svg[]##).

image::diagrams/6-tree-simple.svg[width=85%]

== 6⋮13 Sense

image::sphere-glyphs/sphere-06-13.svg[width=100pt,height=141.4pt]

*Sense:* jŏth-tŏi /d͡ʒɑθ.tɔɪ/

Agents may be blind actors, no more than a self-catalyzing reaction, or the agent may develop the capability of sensing and reacting to its environment.
Sense is the essential element of the encounter of that which is beyond the self.
It is the beginning of external self-organization that leads to external manifestation.
It is an echo of Process yielded through the incompleteness of the agent.

image::diagrams/7-tree-simple.svg[width=85%]

== 7⋮17 Thought

image::sphere-glyphs/sphere-07-17.svg[width=100pt,height=141.4pt]

*Thought:* chō-kou /t͡ʃoʊ.kaʊ̯/

If what is sensed leaves its mark upon the agent then we find the seed for the emergence of representational systems.
The agent can now experience itself in time, forming memories, and gains the ability to not just change behavior based on current circumstance but also based on past learning.
These internal marks can then be sensed and manipulated and so give rise to symbol, language, and communication.

image::diagrams/8-tree-simple.svg[width=85%]

== 8⋮19 Desire

image::sphere-glyphs/sphere-08-19.svg[width=100pt,height=141.4pt]

*Desire:* ät-thĕl /ɑt.θɛl/

Having formed memory the agent now is able to experience the external as something to be sought after or avoided.
Want and fear and all the aspects of emotional attachment emerge.
Desire attaches the agent to the external and so opens a channel for the external to truly manifest.
It is attachment to the world that makes the world.
We regard this as a positive development, an overcoming of the limited solipsistic self through desire.

image::diagrams/9-tree-simple.svg[width=85%]

== 9⋮23 Matter

image::sphere-glyphs/sphere-09-23.svg[width=100pt,height=141.4pt]

*Matter:* ĕ-pĕp /ɛ.pĕp/

Through desire the agent manifests the objectively real.
The external is truly manifest beyond whatever sense, thoughts, or desires the agent may hold regarding it, so completing the self-overcoming of the agent.
The objective binds the agent while also making possible the emergence of the next level of agency within objective reality.
The agent has surrendered its naive omnipotence in its embrace of a new greater level of being in which it only has marginal and indirect power in exchange for a greater state of being.

image::diagrams/10-tree-simple.svg[width=85%]

== 10⋮29 Life

image::sphere-glyphs/sphere-10-29.svg[width=100pt,height=141.4pt]

*Life:* vŭ-sōb /vʌ.soʊb/

The manifestation of objective reality allows the agent to itself become a manifest object.
By surrendering itself into objectivity and becoming limited the agent is able to enter into a space where it can come into authentic contact with other agents manifest as other subjects.
Each aspect of the agent obtains and is constrained by a physical correlation.
For us humans, this is our brains.
Every thought, sense element, and desire is within our brains and is lost to us with disruption of this fragile tissue.

image::diagrams/11-tree-simple.svg[width=85%]

== 11⋮31 Kia

image::sphere-glyphs/sphere-11-31.svg[width=100pt,height=141.4pt]

*Kia:* fĕ-shĕr /fɛ.ʃɛɹ/

Kia is the void which remains within manifestation.
In the twelfth tree all has manifested and yet Nothing remains.
This Nothing is experienced as consciousness, free will, and ecstasy.
More than that, Kia is the basis of having any experience whatsoever.
All of the aspects of manifestation through the agent can carry on quite well without any conscious experience or free choice within it.
In dreamless sleep and in normal waking when on auto-pilot Kia retreats.
Kia manifests as the absurd, wonder, the presence of the undefined and unknown.
Kia can arise in quiet contemplation, ecstatic overload, and in many ways that open the fundamental questions of being.

image::diagrams/12-tree-simple.svg[width=85%]
