= Introduction

Emanant Void Magick is a toolkit for thinking about and manipulating reality.
It provides an open framework of concepts and associations which you are encouraged to freely adapt and build upon.
This framework evolves in layers of increasing complexity, each of which may be applied usefully on its own.
We encourage you to explore the philosophical and practical aspects in parallel as the concepts are best understood through application.

At the heart Emanant Void Magick is an esoteric narrative ontology which describes the process by which being emanates from void to give rise to subjective and objective reality.
This narrative evolves and grows like a tree, budding spheres connected by paths, concepts and their associations.
We encourage you to work slowly through this material, considering in each layer of emanation as whole unto itself.

Magick is active engagement with reality.
We will present a number of practices relating to specific levels of emanation.
The rituals presented may be practiced as described or hopefully adapted to the style of your particular practice.
We adopt the convention of this spelling with a ❝k❞ to distinguish the concept from the art of stage magic and illusion.

This work has been inspired by Hermetic Qabalah, but it is emphatically not Qabalah.
A student of Qabalah will spot a number of similarities, but Emanant Void Magick is not Qabalah.
Hermetic Qabalah arose from syncretism and perennialism,
fusing and distorting a huge number of sources into a new tradition that claimed a universal lineage.
Hermetic Qabalah pulls from Hermeticism, Jewish Kabbalah, Platonism, Christian theology, and more.
Emanant Void Magick is neither syncretic nor perennialist.

We find syncretism problematic as it dilutes its sources and often distorts the material beyond recognition.
In your own practice you should feel free to adapt and remix this source as you see fit.
Emanant Void Magick is designed for remixing by avoiding syncretism.
It is easier to bake a cake with pure ingredients than starting with a cake someone else baked.

Perennialism is similarly problematic as it is often simply an appeal to authority.
Whatever value this work may have must stand on its own without making claim to be the secret revealed wisdom of any tradition.
