= Pentagram of Desire
:figure-caption!:

Just as the initial six spheres gave us a formula for the pentagram,
so the final six may give us a formula for an averse pentagram.
While the initial pentagram was empty, this one has Desire at its center.

.Structure of twelve sphere tree emphasizing pentagram of desire.
image::diagrams/12-tree-pentagram.svg[width=100%]

The Pentagram of Desire symbolizes how our energy flows through attention into being.
In the higher spheres we find archetypes which are echoed in the lower.
The higher spheres describe merely what is in the process of coming into being.
The lower spheres are being within the structure from the higher.
While the higher worlds are causative, the lower worlds are consequence.

As Chaos is the primal source in the higher tree so Desire is the conduit for this source in the lower.
The emanation of Chaos gives rise to Process and Pattern while Desire occurs within the context of Sense and Thought.
Sense echos Process in that it is about allowing sensations to come into being.
Thought echos Pattern in that it organizes and connects the elements of Sense.
Desire emerges from Sense and Thought, an inversion of how Process and Pattern emerge from Chaos.
This inversion speaks to how Desire is influenced by Sense and Thought.

Like how Form and Change emanate from Chaos, Process, and Pattern, so Matter and Soul emanate from Desire, Sense, and Thought.

Desire what makes things matter, and as implied my the language it gives rise to Matter.
Through interaction with Mater it gives rise to Soul.

The neither-neither principle of Soul and Matter gives rise to Kia.

The path of the Devil is the central channel linking the higher spheres to the lower.
